// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzoG8aNNqVoLQc6hO_-iMjxtwQc4PzeeQ',
    appId: '1:693225974571:web:e26e6a4badda4c93ad336e',
    messagingSenderId: '693225974571',
    projectId: 'bank-app-tumtou-168',
    authDomain: 'bank-app-tumtou-168.firebaseapp.com',
    storageBucket: 'bank-app-tumtou-168.firebasestorage.app',
    measurementId: 'G-C85J2V4K1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGGfOo5ebQvG9HXzNDGXt-7-WYuKAPi1U',
    appId: '1:693225974571:android:ae74e0f805d9e963ad336e',
    messagingSenderId: '693225974571',
    projectId: 'bank-app-tumtou-168',
    storageBucket: 'bank-app-tumtou-168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn4zCvNgbGf4h-fXQkebt9f1T5bScVxNk',
    appId: '1:693225974571:ios:99a3f98d8c43fd46ad336e',
    messagingSenderId: '693225974571',
    projectId: 'bank-app-tumtou-168',
    storageBucket: 'bank-app-tumtou-168.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSH_NzO4AV4Y6lLQrC5do39ufvdYK0o60',
    appId: '1:574932336319:ios:e68c7432c6633fb8ed900a',
    messagingSenderId: '574932336319',
    projectId: 'bank-app-tumtou-dev-168',
    storageBucket: 'bank-app-tumtou-dev-168.firebasestorage.app',
    iosClientId:
        '574932336319-1klft763s8go1tntsds8q1drtul1rmme.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0H_GvgT6PJ7B1EM2e9nKCbmVhN-MPMcw',
    appId: '1:574932336319:web:ffb5cf6f82ae8aaeed900a',
    messagingSenderId: '574932336319',
    projectId: 'bank-app-tumtou-dev-168',
    authDomain: 'bank-app-tumtou-dev-168.firebaseapp.com',
    storageBucket: 'bank-app-tumtou-dev-168.firebasestorage.app',
    measurementId: 'G-K399QBPV24',
  );
}